### ISSUE TITLE
fitmodel result class needs residual and svd of residual helper methods

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#112]
* glotaran version: 0099d7bdefd5f79476cee9dc9c008ecd44642443

To evaluate a fitmodel/result (the quality of the fit to the data) one needs to be able to retrieve the residual matrix and conveniently the singular value decomposition of the residual matrix. 

One example for this need is illustrated by issue: https://github.com/glotaran/glotaran-examples/issues/7

**Comment by jsnel** [comment]
Currently lmfit_vapro's SeparableModelResult in result.py has the methods final_residual and final_residual_svd

Suppose that lmfit_varpro would ever by absorbed by lmfit, would it make sense to be so dependent on the API it provides for core functionality?

**Comment by joernweissenborn** [comment]
If thats ever gonna happen, there will much more breaks. That debt is lurking on our shoulder anyway so lets deal with it when the time comes
