### ISSUE TITLE
gta.io.TimeExplicitFile(relpath) looks in working directory rather than relative to calling script

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#113]
* glotaran version: 0099d7bdefd5f79476cee9dc9c008ecd44642443

### Description

Trying to execute a script which calls
dataset = gta.io.TimeExplicitFile("data.ascii").read("dataset1")
while the working directory was set to something else, e.g.
glotaran-examples/wrong_subdir
(if nothing is specified it is automatically set to $HOME)

### What I Did
A workaround which does always work independent of the working directory set
```
script_dir = os.path.dirname(os.path.abspath(__file__))
root_data_path = os.path.join(script_dir, 'data.ascii')
dataset = gta.io.TimeExplicitFile(root_data_path).read("dataset1")
```
### Analysis
Probably the best order of things to look in is:
- check for absolute path
- relative to calling script
- in working directory 
error message if not found

**Comment by joernweissenborn** [comment]
It does work the following way:
``` python
        absfilepath = os.path.realpath(filepath)
   
        if os.path.isfile(filepath):
            self._file = filepath
        elif os.path.isfile(absfilepath):
            self._file = absfilepath
        else:
            raise Exception(f"Path does not exist: {filepath}, {absfilepath}")

```

A user always expects that a relative path is relative to the working dir, never to the script dir.

If you want a script independent of the path, give it an absolute path. If you want script relative path, you have to generate within the script and calculate the absolute path.
