### ISSUE TITLE
get a reader for *.sdt files

### ISSUE THREAD

**Issue by s-weigand** [glotaran/glotaran#124]
Not to reinvent the wheel we should use work already done by other people to read binany files.
For ``*.sdt`` files that would be [Christoph Gohlke](cgohlke@uci.edu) who wrote a reader for [``*.sdt`` ](https://www.lfd.uci.edu/~gohlke/code/sdtfile.py.html) and also some other [fileformats](https://www.lfd.uci.edu/~gohlke/). His files are under BSD licence, so it shouldn't be a problem to use them.

@jsnel since you are the projects manager, can you ask him, if he is fine with us using his work, when we reference him in credits? I think that is a nicer way than just using it.

**Comment by cgohlke** [comment]
Feel free to use/vendor/fork sdtfile.py. Hope it works. Otherwise try [python-bioformats](https://github.com/CellProfiler/python-bioformats/).
