### ISSUE TITLE
Remove the git installation of lmfit-varpro in tests

### ISSUE THREAD

**Issue by s-weigand** [glotaran/glotaran#139]
### Description
Since ``lmfit-varpro`` is on PyPi now there is now need manually install the git version of it.
Also this could lead to falsly passing test, if the minimum required version of ``lmfit-varpro`` wasn't bumped in ``setup.py``.

**Comment by joernweissenborn** [comment]
`lmfit-varpro` dependency is fine.

https://github.com/glotaran/glotaran/blob/master/setup.py#L83
