### ISSUE TITLE
Support for FLIM ascii data format

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#142]
### FLIM Image format 
Given a FLIM image, it is often desirable to select those pixels associated with the subject of interest for modeling. For example, given a FLIM image of a cell, only those pixels interior to the cell wall are typically representative of the fluorescence decay of interest, and accordingly only these pixels are usually selected for modeling. Pre-processing dedicated to pixel selection is performed prior to exporting the data to a FLIM Image format. The indices of selected pixels are then included in the ascii file format.

The format of the input ﬁle is as follows.
```
line 1: reserved for comments, not read
line 2: reserved for comments, not read
line 3: the character string “FLIM Image”
line 4: dimension of image as x y (space-delimited)
line 5: numb er of timep oints t in image
line 6: numb er of pixels x selected for analysis
line 7: vector of the times at which measurements were made
line 8: index of selected pixel and decay trace from this pixel Ψ(,p)
... ...
Line (8+numb er of selected pixels): the character string “Intensity map” t1, t2,..., tm Note that each column represents a decay trace, and each row represents a time-gated spectrum. 
```

**Comment by s-weigand** [comment]
The `Intensity map`, as I just found out, is a map of the pixels (image) with the sum over the time trace  as value for each pixel. So it's basically the timesum of the FLIM.

Btw how exactly did the selection process work?
Fothe the given data I found:
`mean(Intensity map)` = 245.5
`median(Intensity map)`= 73.0
`min(selected pixels)` = 798

PS.: If you want i can drop my data exploration notebook here.

**Comment by SerLap** [comment]
yes the intensity map show an time integral, but can be changed in the gui to have max number in the trace per pixel. 
Selection of the pixels is on the basis  of the intensity image just selecting all pixels that has higher than thresh hold value in the intensity matrix.

**Comment by s-weigand** [comment]
With PR #151 we have legacy support 😄
