### ISSUE TITLE
Implement constraints on the conditional linear parameters

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#41]
There are two constraints on the conditional linear parameters (CLP) e.g. spectra, that are very much needed, especially to be feature par with Glotaran and TIMP:

- zero constraints (put the spectra of a compartment to zero)

- equality constraints (scale the spectra of one compartment to another with a scaling parameter)

The effect of a spectral constraint is that the number of colums in the c-matrix is reduced for the purpose of the variable projection step for each wavelength for each compartment to which the constraint applies. 
In the c-matrix the columns which are in a spectral relation are summed together.

The TIMP implementation can be seen here and it pretty clear:
https://github.com/jsnel/TIMP/blob/develop/pkg/R/doClpConstr.R
(this applies the spectral constraints and removed columns from the c-matrix afterwards)
The most important dependency is:
https://github.com/jsnel/TIMP/blob/develop/pkg/R/getClpConstr.R
(this calculates which compartments are involved)

**Comment by joernweissenborn** [comment]
This is implemented.
