### ISSUE TITLE
Catch lmfit\minimizer.py errors

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#44]
When the starting parameters are particularly bad (especially the location of the IRF), after a few iteration a crash (ValueError: The input contains nan values) will occur. We need to catch this exception and return the results for the last successful iteration and report back the results.

fit_sim_multi_dataset_free_param.py can be used for testing purposes. 

> Traceback (most recent call last):
>   File "glotaran/tests/python/fit_sim_multi_dataset_free_param.py", line 105, in <module>
>     specfit_result = specfit_model.fit()
>   File "glotaran\glotaran\model\model.py", line 46, in fit
>     return self.fit_model().fit(*args, **kwargs)
>   File "glotaran\glotaran\fitmodel\fitmodel.py", line 22, in fit
>     result.fit(*args, **kwargs)
>   File "lmfit-varpro\lmfit_varpro\result.py", line 22, in fit
>     verbose=verbose)
>   File "lmfit\minimizer.py", line 1242, in minimize
>     return function(**kwargs)
>   File "lmfit\minimizer.py", line 1001, in least_squares
>     **kws
>   File "scipy\optimize\_lsq\least_squares.py", line 908, in least_squares
>     tr_options.copy(), verbose)
>   File "scipy\optimize\_lsq\trf.py", line 124, in trf
>     loss_function, tr_solver, tr_options, verbose)
>   File "scipy\optimize\_lsq\trf.py", line 507, in trf_no_bounds
>     f_new = fun(x_new)
>   File "scipy\optimize\_lsq\least_squares.py", line 794, in fun_wrapped
>     return np.atleast_1d(fun(x, *args, **kwargs))
>   File "lmfit\minimizer.py", line 371, in __residual
>     out = _nan_policy(out, nan_policy=self.nan_policy)
>   File "lmfit\minimizer.py", line 1432, in _nan_policy
>     raise ValueError("The input contains nan values")
> ValueError: The input contains nan values

**Comment by joernweissenborn** [comment]
Since we have are omitting  `nan` values now, we should see if there are other minimizer errors are turning up.
