### ISSUE TITLE
Implement numerical convolution of the c-matrix with an (measured) IRF

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#53]
It's possible that the IRF is specified for every time-point (measured externally rather than fitted by one or multiple gaussians). 

In this case the IRF needs to be convolved numerically with the c-matrix. This is very time-consuming thus an efficient method of doing so is desired. See for an example of fast numerical convolution with cython/numpy here: http://cython.readthedocs.io/en/latest/src/userguide/numpy_tutorial.html

In TIMP the different convolution methods are listed in [ntr.c](https://github.com/jsnel/TIMP/blob/master/pkg/src/ntr.c) (Conv1, Conv2, Conv3).

**Comment by joernweissenborn** [comment]
https://docs.scipy.org/doc/numpy/reference/generated/numpy.convolve.html

**Comment by jsnel** [comment]
For reference, the TIMP implementation can be found here: 
https://github.com/glotaran/TIMP/blob/master/pkg/R/calcCirf.R#L75
