### ISSUE TITLE
When number of parameters > 10 they should be printed in natural order

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#58]
It should NOT look like this:

> Function evaluations 1, initial cost 4.0634e+10, final cost 4.0634e+10, first-order optimality 0.00e+00.
> Name     Value      Min      Max   Stderr     Vary     Expr
> p_1        -83     -inf      inf     None     True     None
> p_10         0     -inf      inf     None     True     None
> p_11         0     -inf      inf     None     True     None
> p_2        1.5     -inf      inf     None     True     None
> p_3        0.2     -inf      inf     None     True     None
> p_4       0.02     -inf      inf     None     True     None
> p_5       0.07     -inf      inf     None     True     None
> p_6    0.00016     -inf      inf     None     True     None
> p_7   1.32e+04     -inf      inf     None     True     None
> p_8          1     -inf      inf     None     True     None
> p_9          0     -inf      inf     None     True     None

But like this:

> Name     Value      Min      Max   Stderr     Vary     Expr
> p_1        -83     -inf      inf     None     True     None
> p_2        1.5     -inf      inf     None     True     None
> p_3        0.2     -inf      inf     None     True     None
> p_4       0.02     -inf      inf     None     True     None
> p_5       0.07     -inf      inf     None     True     None
> p_6    0.00016     -inf      inf     None     True     None
> p_7   1.32e+04     -inf      inf     None     True     None
> p_8          1     -inf      inf     None     True     None
> p_9          0     -inf      inf     None     True     None
> p_10         0     -inf      inf     None     True     None
> p_11         0     -inf      inf     None     True     None

Perhaps the package natsort can be leveraged for this
from natsort import natsorted
or we could just refer to the absolute index in the total parameter root structure.

**Comment by joernweissenborn** [comment]
The new ParameterGroups and markdown printing solved this.
