### ISSUE TITLE
A Glotaran result class is needed

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#70]
We need a class object which can be queried for the results from a fitmodel call.

At the start a method should be created which prints the results to standard IO or text file.
Next methods are needed which leverage matplotlib to generate plots (concentrations, spectra (EAS, DAS), with flags to plot subsets etc).  
Finally super methods should be created which leverage the text methods and plotting methods to compile a report, in PDF or in a composite plot.

All of this should be implemented in a separate branch, forked off from develop.
@jsnel will draft up some initial skeleton documentation upon which Sharan can hopefully continue the work.

**Comment by joernweissenborn** [comment]
The `Result` class will be also crucial for the interaction of the user with Glotaran. A user new to global analysis needs the ability to explore the results of what he/her just fitted. 

This is the roadmap:

* Reconsolidate the `SeparableModelResult` class of the `lmfit-varpro` package (@joernweissenborn)
* create a class for each type of result (e.g. 'SasSpectrum') and construct each from a `SeparableModelResult`. E.g. a `SaS` class would use the `SeparableModelResult.estimate_e_matrix` method to estimate the E matrix and rename the result to SaS (or conditionally linear parameters)
* implement the `__string__` method and a `plot` method for each class
* pile them in a GlotaranResult class
* create convenience methods in the result class: makePdf, make Jpg out of SAS of state "PSII"...

**Comment by joernweissenborn** [comment]
I think we don't have time to add e.g. convinece pdf printing at the moment. 

The current result class already supports basic analysis.
