### ISSUE TITLE
Consider switching from Jupyter Notebook to JupityerLab

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/glotaran#74]
Maybe write some plugins to connect with the JupyterLab Data Model.

**Comment by jsnel** [comment]
The use of Jupyter Notebooks is currently very much supportive, they are not yet an integral part of the package, so at this stage I see no reason not to switch to JupityerLab, which is clearly the future of Python.
Ref: https://github.com/jupyterlab/jupyterlab 
"The beta releases are suitable for general usage. For JupyterLab extension developers, the extension APIs will continue to evolve until the 1.0 release." As we are not going to develop extensions (AFAIK) we should be fine to use JupityerLab for the purpose of quickstart files, tutorials and documentation. 

I have considered this issue and am signing off, assigning to @joernweissenborn and @s-weigand. When in agreement, close this issue and create issues for the actual conversion of notebooks and/or creation of JupyterLab notebooks from scratch.

**Comment by joernweissenborn** [comment]
I haven't evaluated it yet, but what we in ASAP is a conviniend way to feed data into Glotaran. I hope that Jupyter Lab can help us with this.
