### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by joernweissenborn** [glotaran/glotaran#75]
Thats the new and shiny way, also keep the typehints in the docs (sphinx)

**Comment by jsnel** [comment]
Agreed. Ref https://docs.python.org/3/library/typing.html 
@joernweissenborn will you pick up this task for the current code base?

**Comment by joernweissenborn** [comment]
of course

Am Mi., 27. Juni 2018 um 01:51 Uhr schrieb Joris Snellenburg <
notifications@github.com>:

**Comment by joernweissenborn** [comment]
this be solved with #2
